[project]
name = "code-embedding"
version = "0.1.0"
description = "Simple example for cocoindex: build embedding index based on source code."
requires-python = ">=3.11"
dependencies = ["cocoindex>=0.1.52", "python-dotenv>=1.0.1"]

[tool.setuptools]
packages = []
